# Generated by Django 3.2.8 on 2021-10-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='profissional',
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade'),
        ),
    ]
