# Generated by Django 3.2.8 on 2021-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20211025_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Whatsapp'),
        ),
    ]
